---
name: Build

on:
  workflow_dispatch:
    inputs:
      kernelBranch:
        description: "WSL2-Linux-Kernel git branch"
        required: true
        default: "linux-msft-wsl-5.15.y"
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs.kernelBranch }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: microsoft/WSL2-Linux-Kernel
          ref: ${{ github.event.inputs.kernelBranch }}

      - name: Install requirements
        shell: bash
        run: |
          sudo apt install build-essential flex bison dwarves libssl-dev libelf-dev cpio qemu-utils

      - name: Build WSL2-Linux-Kernel
        shell: bash
        run: |
          echo "::group::Setup parallel build config"
          NB_CORES=$(grep -c '^processor' /proc/cpuinfo)
          echo "::endgroup::"
          echo "::group::Build kernel"
          make -j$((NB_CORES+1)) -l${NB_CORES} KCONFIG_CONFIG=Microsoft/config-wsl
          echo "::endgroup::"
          echo "::group::Build modules"
          make -j$((NB_CORES+1)) -l${NB_CORES} INSTALL_MOD_PATH="$PWD/modules" modules_install
          sudo ./Microsoft/scripts/gen_modules_vhdx.sh "$PWD/modules" modules.vhdx
          echo "::endgroup::"
          echo "::group::Cleanup"
          make clean && rm -r "$PWD/modules"
          echo "::endgroup::"

      - uses: actions/upload-artifact@v4
        with:
          name: WSL2-Kernel-${{ inputs.kernelBranch }}
          path:
            arch/x86/boot/bzImage
            modules.vhdx
